# Generated by Django 5.0.6 on 2026-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_username', models.CharField(max_length=150)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee_id', 'date')},
            },
        ),
    ]
