# Generated by Django 6.0.7 on 2026-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(choices=[('OFFICE', 'Office (HQ)'), ('REMOTE', 'Remote')], default='OFFICE', max_length=20),
        ),
    ]
