services:
  # Single Unified Full-Stack Service (React Frontend + Django REST API Backend)
  - type: web
    name: novulab
    runtime: python
    buildCommand: cd navulab-frontend && npm install && npm run build && cd ../backend/novulab && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: cd backend/novulab && gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,ems.novulabs.net
      - key: CSRF_TRUSTED_ORIGINS
        value: https://ems.novulabs.net
