import { useState } from "react";
import api from "../api/client";
import { useAuth } from "../context/useAuth";
import { usePaginatedList } from "../hooks/usePaginatedList";
import { PageHeader, Card, EmptyState, Loading, ErrorBanner, Button, Pagination, Avatar } from "../components/ui";

function fmtMoney(n) {
  const v = Number(n);
  if (Number.isNaN(v)) return n;
  return v.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export default function Payroll() {
  const { isFinance, isHR, isAdmin } = useAuth();
  const canManage = isFinance || isHR || isAdmin;
  const endpoint = canManage ? "/api/payroll/payslips/" : "/api/payroll/payslips/my_payslips/";
  const {
    items: payslips, page, count, hasNext, hasPrevious, loading, error, setError, goToPage,
  } = usePaginatedList(endpoint, "Couldn't load payroll.");
  const [showForm, setShowForm] = useState(false);

  const [form, setForm] = useState({
    employee_id: "",
    employee_username: "",
    department_id: "",
    month: new Date().toISOString().slice(0, 7) + "-01",
    basic_salary: "",
    allowances: "0",
    deductions: "0",
  });

  function printPayslip(p) {
    const win = window.open("", "_blank", "width=700,height=900");
    if (!win) return;
    const monthLabel = new Date(p.month).toLocaleDateString(undefined, { month: "long", year: "numeric" });
    win.document.write(`
      <!doctype html>
      <html>
        <head>
          <meta charset="utf-8" />
          <title>Payslip — ${p.employee_username} — ${monthLabel}</title>
          <style>
            body { font-family: 'Inter', Arial, sans-serif; color: #1F2430; padding: 40px; max-width: 560px; margin: 0 auto; }
            .brand { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #1C73C9; padding-bottom: 14px; margin-bottom: 20px; }
            h1 { font-size: 20px; margin: 0; color: #071B2E; }
            .tag { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #1C73C9; font-weight: 700; }
            .muted { color: #8A93A6; font-size: 12px; margin-bottom: 6px; }
            table { width: 100%; border-collapse: collapse; margin-top: 16px; }
            td { padding: 10px 0; border-bottom: 1px solid #E7EAF1; font-size: 14px; }
            td:last-child { text-align: right; font-family: monospace; }
            .net td { font-weight: 700; font-size: 16px; border-bottom: none; padding-top: 16px; }
            .net td:last-child { color: #FF7A45; }
            .footer { margin-top: 32px; font-size: 11px; color: #8A93A6; text-align: center; }
          </style>
        </head>
        <body>
          <div class="brand">
            <h1>Novu Lab</h1>
            <span class="tag">Payslip</span>
          </div>
          <div class="muted">Employee</div>
          <div style="font-size:15px;font-weight:600;margin-bottom:12px;">${p.employee_username}</div>
          <div class="muted">Pay period</div>
          <div style="font-size:15px;font-weight:600;">${monthLabel}</div>
          <table>
            <tr><td>Basic salary</td><td>${p.basic_salary}</td></tr>
            <tr><td>Allowances</td><td>+${p.allowances}</td></tr>
            <tr><td>Deductions</td><td>-${p.deductions}</td></tr>
            <tr class="net"><td>Net pay</td><td>${p.net_pay}</td></tr>
          </table>
          <div class="footer">Generated by Novu Lab Ops Console · Not valid without company stamp</div>
        </body>
      </html>
    `);
    win.document.close();
    win.focus();
    win.onload = () => win.print();
  }

  async function handleCreate(e) {
    e.preventDefault();
    try {
      await api.post("/api/payroll/payslips/", {
        ...form,
        employee_id: Number(form.employee_id),
        department_id: Number(form.department_id),
        basic_salary: Number(form.basic_salary),
        allowances: Number(form.allowances),
        deductions: Number(form.deductions),
      });
      setShowForm(false);
      goToPage(1);
    } catch {
      setError("Couldn't generate payslip — check the fields.");
    }
  }

  return (
    <div>
      <PageHeader
        eyebrow={canManage ? "Finance & HR" : "Personal"}
        title="Payroll"
        icon="fa-solid fa-money-check-dollar"
        action={
          canManage && (
            <Button onClick={() => setShowForm((s) => !s)}>
              <i className={`fa-solid ${showForm ? "fa-xmark" : "fa-plus"}`}></i>
              {showForm ? "Cancel" : "Generate payslip"}
            </Button>
          )
        }
      />

      {!canManage && (
        <p className="text-sm text-muted mb-6 flex items-center gap-2">
          <i className="fa-solid fa-lock text-xs"></i>
          You can only see your own payslips here — that's by design.
        </p>
      )}

      <ErrorBanner message={error} />

      {showForm && (
        <Card className="p-5 mb-6">
          <form onSubmit={handleCreate} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs text-muted mb-1.5">Employee ID</label>
              <input required type="number" className="w-full bg-panel2 border border-line rounded-lg px-3 py-2 text-ink outline-none focus:border-signal"
                value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })} />
            </div>
            <div>
              <label className="block text-xs text-muted mb-1.5">Username</label>
              <input required className="w-full bg-panel2 border border-line rounded-lg px-3 py-2 text-ink outline-none focus:border-signal"
                value={form.employee_username} onChange={(e) => setForm({ ...form, employee_username: e.target.value })} />
            </div>
            <div>
              <label className="block text-xs text-muted mb-1.5">Department ID</label>
              <input required type="number" className="w-full bg-panel2 border border-line rounded-lg px-3 py-2 text-ink outline-none focus:border-signal"
                value={form.department_id} onChange={(e) => setForm({ ...form, department_id: e.target.value })} />
            </div>
            <div>
              <label className="block text-xs text-muted mb-1.5">Month</label>
              <input type="date" required className="w-full bg-panel2 border border-line rounded-lg px-3 py-2 text-ink outline-none focus:border-signal"
                value={form.month} onChange={(e) => setForm({ ...form, month: e.target.value })} />
            </div>
            <div>
              <label className="block text-xs text-muted mb-1.5">Basic salary</label>
              <input required type="number" className="w-full bg-panel2 border border-line rounded-lg px-3 py-2 text-ink outline-none focus:border-signal"
                value={form.basic_salary} onChange={(e) => setForm({ ...form, basic_salary: e.target.value })} />
            </div>
            <div>
              <label className="block text-xs text-muted mb-1.5">Allowances</label>
              <input type="number" className="w-full bg-panel2 border border-line rounded-lg px-3 py-2 text-ink outline-none focus:border-signal"
                value={form.allowances} onChange={(e) => setForm({ ...form, allowances: e.target.value })} />
            </div>
            <div>
              <label className="block text-xs text-muted mb-1.5">Deductions</label>
              <input type="number" className="w-full bg-panel2 border border-line rounded-lg px-3 py-2 text-ink outline-none focus:border-signal"
                value={form.deductions} onChange={(e) => setForm({ ...form, deductions: e.target.value })} />
            </div>
            <div className="sm:col-span-2 lg:col-span-3">
              <Button type="submit">Generate</Button>
            </div>
          </form>
        </Card>
      )}

      {loading ? (
        <Loading />
      ) : payslips.length === 0 ? (
        <EmptyState icon="fa-solid fa-money-check-dollar" title="No payslips yet" />
      ) : (
        <>
          <Card>
            <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-line text-left text-xs uppercase tracking-wide text-muted">
                  {canManage && <th className="px-5 py-3 font-medium">Employee</th>}
                  <th className="px-5 py-3 font-medium">Month</th>
                  <th className="px-5 py-3 font-medium">Basic</th>
                  <th className="px-5 py-3 font-medium">Allowances</th>
                  <th className="px-5 py-3 font-medium">Deductions</th>
                  <th className="px-5 py-3 font-medium">Net pay</th>
                  <th className="px-5 py-3 font-medium"></th>
                </tr>
              </thead>
              <tbody>
                {payslips.map((p) => (
                  <tr key={p.id} className="border-b border-line last:border-0 hover:bg-panel2/50 transition-colors">
                    {canManage && (
                      <td className="px-5 py-3 text-ink">
                        <div className="flex items-center gap-2.5">
                          <Avatar name={p.employee_username} />
                          {p.employee_username}
                        </div>
                      </td>
                    )}
                    <td className="px-5 py-3 text-muted font-mono">
                      {new Date(p.month).toLocaleDateString(undefined, { month: "short", year: "numeric" })}
                    </td>
                    <td className="px-5 py-3 text-muted font-mono">{fmtMoney(p.basic_salary)}</td>
                    <td className="px-5 py-3 text-mint font-mono">+{fmtMoney(p.allowances)}</td>
                    <td className="px-5 py-3 text-rose font-mono">-{fmtMoney(p.deductions)}</td>
                    <td className="px-5 py-3 text-ink font-mono font-bold">{fmtMoney(p.net_pay)}</td>
                    <td className="px-5 py-3 text-right">
                      <Button variant="ghost" onClick={() => printPayslip(p)}>
                        <i className="fa-solid fa-print"></i> Print
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            </div>
          </Card>
          <Pagination page={page} count={count} hasNext={hasNext} hasPrevious={hasPrevious} onPageChange={goToPage} />
        </>
      )}
    </div>
  );
}
