# Generated by Django 6.0.7 on 2026-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seed_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='allowed_wifi_ips',
            field=models.TextField(blank=True, default='127.0.0.1, ::1', help_text='Comma-separated list of allowed office IP addresses'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='wifi_restriction_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
