# Generated by Django 6.0.7 on 2026-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_companyprofile_allowed_wifi_ips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='allowed_wifi_ips',
            field=models.TextField(blank=True, default='182.191.93.131, 192.168.20.210, 192.168.20.1, 26.251.229.52, 127.0.0.1, ::1', help_text='Comma-separated list of allowed office IP addresses'),
        ),
    ]
