# Generated by Django 6.0.7 on 2026-07-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CEO', 'CEO'), ('CTO', 'CTO'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('TEAM_LEAD', 'Team Lead'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
