# Generated by Django 5.0.6 on 2026-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_username', models.CharField(max_length=150)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('month', models.DateField(help_text='Use the 1st of the month, e.g. 2026-07-01')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_by_id', models.IntegerField(help_text='Finance/HR user who generated this')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('employee_id', 'month')},
            },
        ),
    ]
