# Generated by Django 5.0.6 on 2026-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=150)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('employee_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
