# Generated by Django 5.0.6 on 2026-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_username', models.CharField(max_length=150)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick'), ('CASUAL', 'Casual'), ('ANNUAL', 'Annual'), ('UNPAID', 'Unpaid'), ('OTHER', 'Other')], default='CASUAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_by_id', models.IntegerField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
