# Generated by Django 5.0.6 on 2026-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_username', models.CharField(max_length=150)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('summary', models.TextField(help_text='What the employee worked on today')),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('REVIEWED', 'Reviewed')], default='PENDING_REVIEW', max_length=20)),
                ('reviewed_by_id', models.IntegerField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('employee_id', 'report_date')},
            },
        ),
    ]
